Allow creator to delete project via NH
aces/cbrain pull request #1011
Opened 2020-09-15 12:47 UTC by natacha-beck

2020-09-15 13:14 UTC, prioux commented on BrainPortal/app/controllers/nh_projects_controller.rb
> +    respond_to do |format|
Please don't add support for other request types until we need them

2020-09-15 13:15 UTC, prioux commented on BrainPortal/app/controllers/nh_projects_controller.rb
> +    @nh_project.destroy
If the project cannot be destroyed, it would be nice if the user got the reasons, in the flash maybe.

2020-09-15 13:27 UTC, MontrealSergiy commented
Creator or maintainer?

2020-09-15 13:30 UTC, natacha-beck commented
Creator only it was discussed in the issue #1011

2020-09-15 13:37 UTC, prioux commented
I think Sergiy was talking about your message, where you use the word 'creator'.

2020-09-15 17:16 UTC, MontrealSergiy commented
It is not like I care who creator or maintainer. Just want to make sure that we are requester is aware of the choice and wording is consistent with functionality.

2020-09-16 14:39 UTC, prioux commented on BrainPortal/app/views/nh_projects/show.html.erb
> +<script src="/assets/jquery.js"></script>
This won't work in production, assets are precompiled

2020-09-16 14:40 UTC, prioux commented on BrainPortal/app/views/nh_projects/show.html.erb
> +<script src="/assets/jquery.js"></script>
Why do we even need to include this here anyway?

2020-09-16 14:41 UTC, prioux requested changes
The jQuery includes are wrong

2020-09-21 19:22 UTC, merged