breaking lines in boutiques param descriptors resolves #1150
aces/cbrain pull request #1151
Opened 2021-09-13 17:52 UTC by MontrealSergiy

Darius would like to better format long parameter descriptors, so asked to add support for line breaks

2021-09-13 17:54 UTC, prioux commented
Why are you including erb and ERB::Util at all these places?!?? These were never necessary before.

2021-09-13 18:04 UTC, MontrealSergiy commented
To avoid error messages for undefined ` h```  method , namely when running rake

Should I put ERB::Util somewhere else or what?

> Why are you including erb and ERB::Util at all these places?!?? These were never necessary before.

2021-09-13 19:20 UTC, prioux commented on BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
> +    <%%= desc.split("\n").map { |s| h(s) }.join("<br>").html_safe if desc %><<%%= "<br><br>".html_safe if isGroupMember %>
You have a syntax error here, you have one too many `<` (search for `<<`)

2021-09-13 19:21 UTC, prioux commented on BrainPortal/lib/cbrain_task_generators/schema_task_generator.rb
> +require 'erb'
All modifications to `schema_task_generator.rb` are unnecessary

2021-09-13 19:31 UTC, prioux commented on BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
> +        <% groupDescription.split('\n') do |paragraph|%>
That code change does not split lines in the rendered page, there are no new `<br>` introduced

2021-09-13 19:31 UTC, prioux requested changes
Please fix all the problems

2021-09-13 19:35 UTC, prioux commented
I tried with a plain CBRAIN that introduced ONLY the change at line 304 of `BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb` for a field that contains a single "\n" in the description. it works if we fix the syntax error:

Before:
![Screen Shot 2021-09-13 at 15 27 53](https://user-images.githubusercontent.com/777588/133145362-4226b2b0-4fb7-473e-a2c3-2f93621628d8.png)
After:
![Screen Shot 2021-09-13 at 15 28 47](https://user-images.githubusercontent.com/777588/133145396-becd90a2-4f85-44db-91a8-05ecad824f2a.png)

There was absolutely no need for any of the changes in the schema task generator.

2021-09-13 19:38 UTC, MontrealSergiy commented
ok, will do

2021-09-20 17:53 UTC, closed without merging

2021-09-20 17:56 UTC, MontrealSergiy commented
Yes, with one line change, no import is needed. I guess it is better than nothing