Fix view in boutique integrator #1127
aces/cbrain pull request #1165
Opened 2021-10-27 14:36 UTC by natacha-beck

2021-11-17 20:39 UTC, prioux commented
I'd like the same changes applied to the new integrator. Sorry! :-)

2021-11-18 18:27 UTC, prioux requested changes
See comment

2021-11-22 17:52 UTC, prioux commented on BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
> +  <span class="tsk-prm-par">
I think that's a bug here, did you mean `</span>` instead?

2021-11-22 17:57 UTC, natacha-beck commented
Yes.

On Mon, 22 Nov 2021 at 12:52, Pierre Rioux ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In
> BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
> <https://github.com/aces/cbrain/pull/1165#discussion_r754510571>:
>
> > @@ -94,6 +94,12 @@
>    </label>
>  <%% end %>
>
> +<%% paragraph = lambda do | text | %>
> +  <span class="tsk-prm-par">
> +    <%%= text   %>
> +  <span class="tsk-prm-par">
>
> I think that's a bug here, did you mean </span> instead?
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/aces/cbrain/pull/1165#pullrequestreview-812852371>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAF525X5ZO2NXJDGZXYRQJDUNJ7OHANCNFSM5G2QWMDA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-22 20:53 UTC, natacha-beck commented
No need to get the same logic within the new integrator, you only support launching multiple tasks with a cbcsv file.

2021-11-22 20:57 UTC, prioux commented
Can you double check that the message in the section "launching multiple tasks" in

BrainPortal/cbrain_plugins/cbrain-plugins-base/cbrain_task/boutiques_task/views/_edit_help.html.erb

is appropriate?

2021-11-24 21:11 UTC, prioux requested changes

2021-11-24 21:11 UTC, prioux commented on BrainPortal/lib/cbrain_task_generators/templates/task_params.html.erb.erb
> -  <%- if param['description'] -%>
This will remove the descriptions of all other inputs if the decriptor is a single_file scenario. Not what you wanted.

2021-11-25 20:31 UTC, merged