Special module support in new Boutiques integrator
aces/cbrain pull request #1181
Opened 2021-11-30 15:24 UTC by prioux

This adds support for including automatically special modules in the class that implements a new boutiques task integration.

This PR comes with the framework modification to support this features, and two sample (and fully operational) modules for adding new validation rules for files based on types or names.

This is very similar to what is described in https://prioux.github.io/new-boutiques-presentation/#/desc_modules except I changed the syntax somewhat. See the comment block at the top of the modules for more info.

2021-12-13 17:50 UTC, prioux commented
Code review please?

2021-12-14 17:38 UTC, MontrealSergiy commented
Look's like some bug. Or may be I did escape something wrong ```    "custom": {
        "cbrain:readonly-input-files": true,


        "cbrain:integrator_modules": {
            "BoutiquesFileNameMatcher": {
               "sinput2": "^a-zA-Z0-9]*\\.txt$",
               "minput2": "^[a-zA-Z0-9]*$"
            },

           "BoutiquesFileTypeVerifier": {
             "sinput2": [ "TextFile", "MincFile" ]
           }
       }

    }``` ![image](https://user-images.githubusercontent.com/11949081/146050241-7eeb1e41-af62-4c95-959c-d933e54a5694.png)

2021-12-14 17:40 UTC, MontrealSergiy commented
![image](https://user-images.githubusercontent.com/11949081/146050983-fd3d8320-8c9a-45ad-aefe-f271c630ea3d.png)

2021-12-14 17:42 UTC, prioux commented
Check your regexp for sinput2, you're missing a opening square bracket.

Please try to solve these issues yourself, by the way/?

2021-12-14 18:36 UTC, MontrealSergiy commented
Seems work with simple files. However the regex validation applies to Cbrain File list name, not the content. 
![image](https://user-images.githubusercontent.com/11949081/146059259-a2ae0eca-e95e-4124-9e13-6dbc60d3904c.png)

2021-12-14 18:40 UTC, MontrealSergiy commented
the collection files conform to regex, and renaming file list helps. 
![image](https://user-images.githubusercontent.com/11949081/146059823-8a215401-09ed-47be-a466-a9be4b3afd09.png)

2021-12-14 18:58 UTC, prioux commented
I don't understand what you're saying in `However the regex validation applies to Cbrain File list name, not the content.` and `the collection files conform to regex, and renaming file list helps.`

Can you please 1) explain properly 2) avoid screenshots unless they're really necessary and show an interface problem?

2021-12-14 21:29 UTC, MontrealSergiy commented
Regex name validation should be applied to each file name in cbcsv file collection rather than, as it apparently done, to the name cbcsv collection file. There is no value in validating the cbcsv file name, it only confuses the user. Is it more clear now

2021-12-14 21:45 UTC, MontrealSergiy requested changes
Generally works yet Cbcsv file support can be improved.


 Regex name validation should be applied to each file name in cbcsv file collection rather than, as it apparently done, to the name cbcsv collection file. There is no value in validating the cbcsv file name, it only confuses the user. 


Perhaps error messages can be improved. Ideally custom module DSL (format) should be validated early at integration step, but perhaps one day a separate cli tool can be developed for scientific software  integrators, who don't have cbrain on their work machines. Not sure is word module clear enough for average integrator I would use word enhancement or addon.

2021-12-15 19:32 UTC, prioux commented on BrainPortal/lib/boutiques_file_type_verifier.rb
> +        params_errors.add(input.cb_invoke_name, "is not of the proper type (should be #{typenames.join(",")})")
I don't know what to_sentence() is, but it's good enough.

2021-12-15 19:34 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_matcher.rb
> +      regex = Regexp.new(regexstring)
It's not the scope of the CBRAIN code to make sure a descriptor is valid, if there is a crash then the administrator will find out soon enough. Descriptors are installed by an admin, after all, not users.

2021-12-15 19:49 UTC, merged