[REFACTORING] of size condition for has_viewer
aces/cbrain pull request #1215
Opened 2022-03-10 20:46 UTC by natacha-beck

2022-03-10 20:53 UTC, prioux commented
If you want to be fancy and do some meta programming, you could add a method_missing handler to single file so that in subclasses, someone could do

```
has_viewer blah blah, :if => :size_allows_viewing_400mb?
has_viewer blah blah, :if => :size_allows_viewing_20kb?
has_viewer blah blah, :if => :size_allows_viewing_2000?
```

or any other method name with that pattern, and dynamically the method woudl be created and it would invoke `size_allows_viewing(number)`. E.g it would dynamically create

```
def size_is_at_least_400mb?
    size_allows_viewing(400_000_000)
end
```

it's a good exercise in meta programming. Supporting the suffixes (kb, mb etc) is optional, it could all be bytes.

2022-03-11 18:09 UTC, prioux requested changes
Review

2022-03-11 19:39 UTC, prioux commented
Well, it's not meta programming, you're not defining the methods dynamically, you're just running the code in method_missing....

Also, the if/else structure is too complicated.

2022-03-11 19:46 UTC, natacha-beck commented
I still define the method on the fly.

I can simplify the `if else`: 

```ruby
  def method_missing(name, *args)
    # Define a method that perform size verifictaion on the file
    # in order to know if it's viewable or not
    size = name.to_s.match(/^size_allows_viewing_(.+)/)[1]
    return super if !size

    size_limit      = size.to_i
    userfile_errors = []
    if self.size.blank?
      userfile_errors.push("No size available for this file")  
    else
      userfile_errors.push("File is too large to be viewable (> #{size.humanize} kB)") if self.size > size_limit
    end

    rescue
      super
  end
```

2022-03-11 19:49 UTC, prioux commented
See my example. You are not defining any method, you are running the code check code within method_missing itself. That's not meat programming.

2022-03-11 20:09 UTC, prioux commented
Actually I just realized that in my example, `method_name` is the same as `name`

2022-03-11 21:41 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/csv_file/csv_file.rb
> +  has_viewer :name => 'CSV Viewer', :partial  => :csv_file, :if => Proc.new { |u| u.size_allows_viewing_400_000 }
The entire point of the exercise was to simplify the job of the developer when configuring the `if` callback... and you still use a Proc... ? Did you forget?

2022-03-11 21:43 UTC, prioux requested changes
See new comments. There are two Proc.new that are not needed anymore

2022-03-14 18:44 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s.humanize} kB) ") if self.size > size_limit
What does the .humanize do ?

2022-03-14 18:49 UTC, natacha-beck commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s.humanize} kB) ") if self.size > size_limit
For example: 

```ruby
NaN main :001 > "400_000".humanize
 => "400 000" 
```

2022-03-14 18:53 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s.humanize} kB) ") if self.size > size_limit
But this can never happen in your code.

2022-03-15 03:46 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s} kB) ") if self.size > size_limit
The message is wrong, it says `size_limit kb` but the limit is in bytes, as implemented.

You have to decide what the meaning of the 400_000 is. Is it bytes or kilobytes?

2022-03-16 19:47 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s} kB) ") if self.size > size_limit
You can also just change the message, by replacing `kB` with `bytes`.

2022-03-16 19:49 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/single_file/single_file.rb
> +      userfile_errors.push("File is too large to be viewable (> #{size_limit.to_s} kB) ") if self.size > size_limit
However, if you do that, then when a programmer wants to specify a limit of 5 gigabytes for viewing a file, they'll have to do 

```
has_viewer ...., :if => :size_allows_viewing_5_000_000_000
```

which is quite long and has a lot of zeros.

2022-03-18 15:42 UTC, merged