Inputcopy
aces/cbrain pull request #1299
Opened 2023-01-27 23:29 UTC by MontrealSergiy

This to reduce corruption of input data and race conditions with input mutating scientific tools, see #1241 for description

2023-01-30 01:20 UTC, MontrealSergiy commented
test boutiques at https://github.com/MontrealSergiy/cbrain-plugins-test/blob/main/boutiques_descriptors/copy_flag_demo.json

2023-02-02 20:49 UTC, prioux commented
I don't really want a new attribute in the tool config structure, rather I want a simple implementation that just copies files when make_available is called with a new option:

```ruby
def make_available(userfile, file_path, userfile_sub_path = nil, start_dir = nil, copy_files = false)
```

On the Boutiques descriptor side, all I want is support for:

```json
    "custom": {
        "cbrain:full-copy-input-files": [ "inputid1", "inputid2", "inputid3" ],
```

2023-02-02 20:51 UTC, prioux requested changes
See my previous comment.

* Remove all tool config changes
* Add copy_files option to make_available()
* Adjust BTQ integrator to set copy_files to true when calling make_available

2023-03-15 21:29 UTC, MontrealSergiy commented
> * BTQ integrator to set copy_files

Note that I see several uses of make_available, besides the BTQ integrator e.g. i
such as boutiques_input_subdir_maker, bids_app_maker

Should I address them too? Would dev continue to use it in modules ?

probably, it safer to pull property automatically, maybe yet another parameter copy_input_as_in_boutiques?


should I add copy_input there too?

2023-03-17 14:05 UTC, MontrealSergiy commented
Looks like rebase gone wrong still working

2023-04-20 15:52 UTC, prioux commented
Please also look at supporting this option in the original Boutiques integrator. This code only supports the new integrator. If it's too complicated, let me know. We don't use the old integrator anymore, so maybe it's not worth it.

2023-04-20 15:52 UTC, prioux requested changes
Bugs and adjustements.

2023-04-20 15:52 UTC, prioux commented on BrainPortal/app/models/boutiques_cluster_task.rb
> +        copy_file = descriptor.custom.dig('cbrain:full-copy-input-files')&.include?(input.id)
You are extracting this option twice, once at line 86 and once at line 95, and at line 95 you are also doing it within an internal loop. This flag doesn't change over time, extract it just once for the input, at around line 83!

2023-04-20 15:52 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +        # Do nothing is symlink already exists with proper value.
You moved the comment block that explains the logic of the `unless` statement UNDER the unless statement, why? That makes the code more difficult to understand.

2023-04-20 15:52 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +      return userfile.cache_copy_to_local_file(full_path) if copy_file
This doesn't work if the caller of make_available() has specified a `userfile_sub_path` in argument. You're only supporting the case where we need a full copy of a FileCollection, but the not case where we need a copy of a partial subtree/subfile.

2023-11-21 02:17 UTC, MontrealSergiy commented
rebased

2025-03-07 21:56 UTC, prioux commented
I am closing this PR without merging because anyway we now have a modules that does this sort of thing.

2025-03-07 21:56 UTC, closed without merging