HTML model and viewer plugin
aces/cbrain pull request #1354
Opened 2023-10-11 14:33 UTC by MontrealSergiy

an html file viewer with a iframe sandbox wrap.

Resubmitted PR after debasing to master as old was failing ci

2025-03-17 15:33 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +HTML was sandboxed and filtered for greter safety
"greter" ?

2025-03-17 15:34 UTC, prioux requested changes

2025-03-17 15:34 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +<%= link_to h("Open in a separate tab"), url_for(:controller  => :userfiles, :id  => @userfile.id, :action  => :display, :viewer => :html, :content_viewer => "on", :file_name => @userfile.name), :tar
Is this link just opening the same current page in a new tab, or something different from the current page?

In which situations would "params[:action]" not be "show" ?

2025-03-17 21:00 UTC, MontrealSergiy commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +<%= link_to h("Open in a separate tab"), url_for(:controller  => :userfiles, :id  => @userfile.id, :action  => :display, :viewer => :html, :content_viewer => "on", :file_name => @userfile.name), :tar
That link opens other userfile in iframe, without the meta info. 

The condition lets me hide this link, assuming there is no need to show.

The action in that case is `display`

That said can delete this condition or any line if you are not comfortable.

2025-03-20 13:28 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +HTML was sandboxed and filtered for greter safety
Why did you resolve this comment? I was pointing out a typo. "greter" is misspelled.

2025-03-20 13:30 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +HTML was sandboxed and filtered for greter safety
The sentence could be made better:

```
This HTML document was sandboxed and filtered for greater safety. If you trust the content of the file, you can <%= link_to "Show it in a separate tab, without sandboxing" ... %>.
```
```

2025-03-20 13:32 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +<%= link_to h("Open in a separate tab"), url_for(:controller  => :userfiles, :id  => @userfile.id, :action  => :display, :viewer => :html, :content_viewer => "on", :file_name => @userfile.name), :tar
OK

2025-03-20 13:32 UTC, prioux requested changes
Small changes in sentences

2025-03-20 17:43 UTC, MontrealSergiy commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +HTML was sandboxed and filtered for greter safety
I likely meant to revisit the wording day later but forgot to push the update, sorry. 

The suggested phrasing is great, though I'd put 'you can open' instead of 'we can display'—it feels more direct and empowering.

2025-03-20 17:56 UTC, MontrealSergiy commented
I skipped the comma in the link label, seems redundant

2025-03-20 17:57 UTC, prioux commented
Remember to test your helper in the console, to make sure it does what you expect.

2025-03-20 18:01 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +<%= link_to(
Can you please restructure this the 'standard' way? e.g.

```erb
  <% if page_is?('#show') %>
    <%= link_to ... %>
  <% end %>
```

The reason is, your big `<%=` block is reduced to nil of the condition is false, but we have to read all the way until the end to realize that it can print nothing.

2025-03-24 21:07 UTC, MontrealSergiy commented
Maybe drop "open without sandboxing", seems open for varios fishing and cross-site forgery? Or limit to file author

2025-03-24 21:28 UTC, prioux reviewed
I made a comment but no need to change things. I will run the viewer on my dev env now.

2025-03-24 21:28 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +      h("Open in a separate tab"),
You know you don't have to h() the link name in link_to(), it will do it automatically? And in any case, your constant string doesn't need any HTML escaping, it's just "Open in a separate tab" which stays exactly the same...

2025-03-24 22:19 UTC, prioux commented
The 'separate tab with sandboxing' mechanism doesn't work right. I get a tiny region with scrollbars and underneat and to the right, your message's layout is not properly on a separate line. See screenshot. Can you please make sure you add `<p>` and `<br>`  between your messages?

![Screenshot 2025-03-24 at 6 14 03 PM](https://github.com/user-attachments/assets/f66ec280-99b9-4146-9b86-8046406b8d7b)

For this test I save a CBRAIN page as HTML and re-uploaded it.

In the new tab, an inspect reveal the iframe has these attributes:

```
<iframe class="full-frame" sandbox="" src=...
```

I'm not sure of sandbox is supposed to have an empty string?

2025-03-24 23:03 UTC, prioux commented
I'm sending you two HTML files on Slack, please make sure your viewer works with both, even when changing back between TEXT mode and HTML mode. I can't get your PR to work right, myself. Also, adjust the layouts!

2025-03-25 02:39 UTC, MontrealSergiy commented
> I'm not sure of sandbox is supposed to have an empty string?
as far I got it empty sandbox means stricter sandbox, but if you would like to allow

- same origin
- scripts
- forms
- top navigation

we add those as attribute values. Please indicate if you like to enable any of above

2025-03-25 03:31 UTC, MontrealSergiy commented
I rolled back size of tab iframe by cost of using hardcoded html style. Tell me if It worth to put proper css.

Text file behavior was not changed. Files ended with html are not shown directly (only via link)
So would you prefer

- change the default behavior
- remove text viewer
- add 'html source' viewer
...

2025-03-26 13:50 UTC, prioux commented on BrainPortal/cbrain_plugins/cbrain-plugins-base/userfiles/html_file/views/_html.html.erb
> +            url_for(
I'm not sure why you are using such a low-level URL builder when we have higher level route helpers. Your URL should be built with:

```ruby
display_userfile_url(@userfile,
  :viewer         => :html,
  :content_viewer => "on",
  :file_name      => @userfile.name
)
```

This helper knows already about the action, the controller, and where to put the ID of the userfile inside it.

2025-03-31 18:15 UTC, MontrealSergiy commented
1. I am not yet sure if it is a good idea to grant any permissions to an HTML file opened without warning the user. However, based on our recent discussions, I have slightly relaxed sand-boxing and removed the second "open in the new tab as is, without sand-boxing link.

I hope it is closer to what you wanted, though it might be not.

2. Not sure maybe If would prefer to drop sandboxing completely, we put some confirmation button before rendering HTML below the metadata. 

3. The bug where links disappeared after switching to text mode and back has been fixed using an auxiliary query parameter, page helper does not work here for me.

2025-03-31 23:14 UTC, prioux commented
I think this code is now fine. The decisions you made regarding sandboxing are also fine. We can revisit the viewer later if necessary, but this works correctly.

2025-03-31 23:21 UTC, merged