Sti boot check#969
aces/cbrain pull request #1369
Opened 2024-02-01 21:29 UTC by MontrealSergiy

see #969

2024-02-02 17:51 UTC, MontrealSergiy commented
I think I can further shorten code but factoring out common elements of two checks into another method. Also if changes will be needed (e.g. rollback to using rescue requested) I would need less change  ... so if it is ok wait a sec

2024-02-02 19:51 UTC, MontrealSergiy commented
added a generic STI checking methods and a task check for Bourreau

2025-03-13 15:56 UTC, prioux commented
I think this PR is fine. I would add more check on more tables however:

* groups
* custom_filters
* users
* remote_resources
* data_providers
* background_activities
* resource_usage
* messages
* disk_quotas

(All of these, only during the portal system checks)

2025-03-13 16:00 UTC, prioux commented
I would also modify the traces. The banned

```
#----------------------------------------------------------------------------
puts "C> Checking STI column of #{table} ..."
#----------------------------------------------------------------------------
```

shoudl appear only once in the script, and print only a single line for all STI checks, then be followed by a single log lone per tabel checks (each optionally followed by their warning messages if any). Something like

```
C> Checking Single Table Inheritance classes ...
C>    - Checking table 'userfiles'
C>    - Checking table 'cbrain_tasks'
C>       ERROR: type 'CbrainTask::StupidTool' is not defined!
C>    - Checking table 'blahblah'
```

2025-03-20 14:02 UTC, prioux commented
Still waiting for updates.

2025-03-31 22:07 UTC, MontrealSergiy commented
disk_quota is not yet sti.

2025-04-02 14:57 UTC, prioux commented
I think overall the code is ok, I'm just a bit not sure for the overall structure of where the code is run.

1. Why is the Userfile table checked separately? We'll get twice the exact same boot message "C> Checking Single Table Inheritance classes"
2. Why not do all the checks at the end of the common "cbrain_system_checks.rb", so that both Bourreaux and Portal verify everything? That way we don't modify at all the portal_system_checks, nor the bourreau_system_checks. I understand we wanted the Bourreau code to check only the rows assigned to itself, but that can be done in the cbrain_stystem_checks with something like

```ruby
   (myself.is_a?(Bourreau) ? CbrainTask.where(:bourreau_id => myself.id) : CbrainTask)
```

in the list of models to pass to validate_sti()

2025-04-02 15:21 UTC, prioux commented on BrainPortal/lib/cbrain_checker.rb
> +    table = query&.table_name || 'a table'
table should never be blank, and .table_name should never be invoked on a nil so that line should be made straighforwardly:

```ruby
  table = query.table_name
```

2025-04-02 15:27 UTC, prioux requested changes
See comments

2025-04-02 15:27 UTC, prioux commented on BrainPortal/lib/portal_system_checks.rb
> +  def self.z040_ensure_sti_enabled #:nodoc:
replace "enabled" with "valid" because it's not like STI is something that can be enabled or disabled

2025-04-02 16:14 UTC, prioux commented
So I just verified that the class check code cannot go into the common cbrain_system_checks because the models aren't yet fully loaded at that time.

2025-04-02 16:30 UTC, prioux commented
This is what I cam up with instead:

```diff
diff --git a/BrainPortal/lib/portal_system_checks.rb b/BrainPortal/lib/portal_system_checks.rb
index 857dc4bdb..63b4d3325 100644
--- a/BrainPortal/lib/portal_system_checks.rb
+++ b/BrainPortal/lib/portal_system_checks.rb
@@ -95,6 +95,40 @@ class PortalSystemChecks < CbrainChecker #:nodoc:
 
 
 
+  def self.a025_check_single_table_inheritance_types
+
+    #-----------------------------------------------------------------------------
+    puts "C> Checking 'type' columns for single table inheritance..."
+    #-----------------------------------------------------------------------------
+
+    myself      = RemoteResource.current_resource
+    err_or_warn = Rails.env == 'production' ? 'Error' : 'Warning'
+    errcount    = 0
+
+    [
+      Userfile,
+      (myself.is_a?(Bourreau)? myself.cbrain_tasks : CbrainTask),
+      CustomFilter,
+      User,
+      RemoteResource,
+      DataProvider,
+      BackgroundActivity,
+      ResourceUsage,
+      Invitation,
+    ].each do |query|
+      badtypes = query.distinct(:type).pluck(:type).compact
+        .reject { |type| type.safe_constantize }
+      next if badtypes.empty?
+      puts "C> \t- #{err_or_warn}: Bad type values in table '#{query.table_name}': #{badtypes.join(', ')}"
+      errcount += 1
+    end
+
+    raise "Single table inheritance check failed for #{errcount} tables" if Rails.env == 'production' && errcount > 0
+
+  end
+
+
+
   def self.a030_ensure_we_can_load_oidc_config
 
       #----------------------------------------------------------------------------
```

2025-04-02 16:33 UTC, prioux commented
About my patch: the check method should work fine at a025 for both portals and bourreaux; the checking code could be extracted but I don't mind repeating the check in both files too.

2025-04-02 16:42 UTC, prioux commented
About my patch 2: it worked on the Bourreau side too, except a) there is no Invitation model on the bourreau side (by design) and 2) my fancy `myself.cbrain_tasks` needs to be replaced with a `CbrainTask.where(:bourreau_id => myself.id)`

2025-04-02 16:49 UTC, prioux commented
Given I've got a solution, I'll just commit it and close this PR

2025-04-02 16:49 UTC, closed without merging

2025-04-02 16:51 UTC, MontrealSergiy commented on BrainPortal/lib/cbrain_checker.rb
> +      "C> \t\t #{level}: Invalid STI type: #{name || '(blank value)'}" unless name.present? && name.safe_constantize
Agree using both `name.present?` and `blank value` overkill. But I would keep at the least blank value.
It might happens with some, perhaps buggy tables, such as `messages`

Please confirm

2025-04-02 16:59 UTC, prioux commented
All implemented by me in https://github.com/aces/cbrain/commit/93d0473fa1c8b6480025e1f30366b5905e97e3f0