Log overlay in task
aces/cbrain pull request #1392
Opened 2024-05-14 03:11 UTC by MontrealSergiy

#1387

2025-03-07 02:35 UTC, prioux requested changes
Minor changes.

Also please make sure the resulting addlog() messages look good, that the stuff substituted in them (e.g. with #{var}) makes nice sentences.

2025-03-07 02:35 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    self.addlog("Overlaying ext3 capturing basenames #{names}")
Don't addlog() in a method that could be called just to fetch some information. Addlog when the information is used instead (so at the place where the method is called).

2025-03-07 02:35 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    self.addlog("Overlaying ext3 capturing basenames #{names}")
E.g. when calling the method in the console.

2025-03-07 02:35 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    overlay_paths = self.tool_config.singularity_overlays_full_paths.map do |knd, id_or_name, paths|
This is a bit too vervose. We don't need one line to say "processing" (line 2387), then one line that says "checking" (2389) just to finally get the line that we want, at 2492. Limit yourself to a single, simpler:

```
"Overlay configured: {type} {path}"
```

2025-03-07 02:35 UTC, prioux commented on BrainPortal/app/models/tool_config.rb
> +      next ["Local File", knd, [knd]] if knd =~ /^\//  # FIXME delete it after successful migration
The old style doesn't exist anymore, so remove this completely.

2025-03-10 20:33 UTC, MontrealSergiy commented on BrainPortal/app/models/cluster_task.rb
> +    overlay_paths = self.tool_config.singularity_overlays_full_paths.map do |knd, id_or_name, paths|
For userfiles would you prefer log database id or path is ok?

2025-03-10 20:49 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    overlay_paths = self.tool_config.singularity_overlays_full_paths.map do |knd, id_or_name, paths|
Just the basename of the file is fine.

2025-03-11 20:40 UTC, MontrealSergiy commented
something like that read ok?


```
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: local file /data1/user-data/sboroday/dps/sqs16.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: local file /data1/user-data/sboroday/dps/sqs15.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: local file /data1/user-data/sboroday/dps/sqs-001.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: local file /data1/user-data/sboroday/dps/sqs16.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: registered userfile sqs1.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: Data Provider /data1/user-data/sboroday/dt/sqfs/ICBM2.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: local file /data1/user-data/sboroday/dps/sqs15.sqs
[2025-03-11 14:27:29 CST] singularity_commands() Overlay configured: Data Provider /data1/user-data/sboroday/dt/sqfs/yetanother.sqs
```

2025-03-11 20:46 UTC, prioux commented
Sure, that looks nice.

2025-03-12 14:51 UTC, merged