Optimise task binding of local provider folders
aces/cbrain pull request #1401
Opened 2024-07-02 21:31 UTC by MontrealSergiy

2025-03-06 16:20 UTC, prioux requested changes
Minor changes

2025-03-06 16:20 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +  # This determines if the task expects to only read its input files,
Can you do me a favor? The method `file_access_symbol` is defined exactly the same way in two other files, boutiques_portal_task.rb and boutiques_cluster_task.rb, and now you're adding it to cluster_task.rb. I think we should just have one copy directly in cbrain_task.rb, the superclass of everything.

I woudl added just below self.properties at line 266 of cbrain_task.rb

2025-03-06 16:20 UTC, prioux commented on BrainPortal/app/models/boutiques_cluster_task.rb
> +    return Userfile.where(id: file_ids).map &:data_provider
You are returning a list with duplicate data providers in it (e.g. when two input files are on the same DP)

2025-03-08 00:05 UTC, MontrealSergiy commented on BrainPortal/app/models/boutiques_cluster_task.rb
> +    return Userfile.where(id: file_ids).map &:data_provider
I never claimed it returns unique dp(s).

2025-03-10 13:55 UTC, MontrealSergiy commented on BrainPortal/app/models/cluster_task.rb
> +  # This determines if the task expects to only read its input files,
This will place the method into the section is called  Task Launch API. Are you sure? To me it is more of utility or core method section.

Or maybe create new subsection, perhaps  'access control' ,

2025-03-10 14:11 UTC, MontrealSergiy commented on BrainPortal/app/models/boutiques_cluster_task.rb
> +    return Userfile.where(id: file_ids).map &:data_provider
But now it returns unique dp

2025-03-10 15:24 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +  # This determines if the task expects to only read its input files,
Well, there isn't a good place in the code for this method, and you're right it is kind of in a category of its own. It's not really a utility either. Let me look at the file and find a good place for it. Give me 10 minutes.

2025-03-10 15:31 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +  # This determines if the task expects to only read its input files,
Right, so I guess you can put it in the `Utility Methods` section, at the end.

Make sure you maintain three blank lines after the method's final `end` before the banner for the next section, the one called `Useful ID Generators`. My convention is three blank lines just before each banner.

2025-03-10 18:26 UTC, MontrealSergiy commented
empty lines corrected

2025-03-10 18:30 UTC, merged