Add admin option to enable/disable compression when archiving tasks #1123
aces/cbrain pull request #1423
Opened 2024-08-26 22:39 UTC by MontrealSergiy

see #1123 an option is added to the Archive panel in the list

2025-01-21 21:25 UTC, prioux commented on BrainPortal/app/controllers/tasks_controller.rb
> +    nozip           = params[:nozip].presence  && current_user.has_role?(:admin_user) # for archiving without compression, admin only
use `.present?` not `.presence`, they're not the same thing

2025-03-04 15:18 UTC, prioux commented
Please rebase to master branch and address my comment at line 711

2025-03-05 18:11 UTC, prioux requested changes
Minor changes.

2025-03-05 18:11 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    tar_file      = self.in_situ_workdir_archive_file false  # first assume tar file is gzip-compressed
Add parens here too

2025-03-05 18:11 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +        self.addlog("Cannot unarchive: tar archive #{tar_file} does not exist.")
This message will be printed even if the tar archive IS found two lines below. I think that's misleading. The original code with a single 'addlog()' statement was better. So please undo this (remove new line 1483 and revert new line 1486)

2025-03-05 18:11 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
>      full=self.full_cluster_workdir
Why remove the blank line? I like blank lines that properly separate small pieces of code. Small paragraphs that do things related to each other.

2025-03-05 18:11 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    # todo 'file' command can be used to reliably determine actual archive type, Alpine etc ...
Remove spurious comments (1619,1620). Yes we know we could make a more formal check, but there is no point in writing this down here.

2025-03-05 18:12 UTC, prioux commented
Not just minor changes, also one important bug.

2025-03-05 21:53 UTC, MontrealSergiy commented on BrainPortal/app/models/background_activity/archive_task_workdir.rb
> +    ok           = cbrain_task.archive_work_directory(nozip)                              if dest_dp_id.blank?
freshly introduced

good catch

2025-03-06 15:22 UTC, prioux commented on BrainPortal/app/models/background_activity/archive_task_workdir.rb
> +    ok           = cbrain_task.archive_work_directory(nozip)                              if dest_dp_id.blank?
This means you didn't actually ran your code right? Use the console! RUN your code!

2025-03-07 22:20 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +        self.addlog("Cannot unarchive: tar archive #{tar_file} does not exist.")
I am still waiting for this to be addressed

2025-03-07 22:20 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
>      full=self.full_cluster_workdir
Also please return the blank line

2025-03-07 22:21 UTC, prioux commented on BrainPortal/app/models/cluster_task.rb
> +    # todo 'file' command can be used to reliably determine actual archive type, Alpine etc ...
Do this

2025-03-07 22:40 UTC, MontrealSergiy commented on BrainPortal/app/models/cluster_task.rb
> +        self.addlog("Cannot unarchive: tar archive #{tar_file} does not exist.")
rolled back

2025-03-07 22:40 UTC, MontrealSergiy commented on BrainPortal/app/models/cluster_task.rb
>      full=self.full_cluster_workdir
rolled back

2025-03-07 22:41 UTC, MontrealSergiy commented on BrainPortal/app/models/cluster_task.rb
> +    tar_file      = self.in_situ_workdir_archive_file nozip
ok

2025-03-10 15:22 UTC, prioux requested changes
Insert a blank line that disappear.

2025-03-10 18:54 UTC, merged