Use a dedicated helper to check current controller action in views
aces/cbrain pull request #1428
Opened 2024-09-06 18:21 UTC by MontrealSergiy

a separate commit contains few simplifications of the old neurohub code 

https://github.com/aces/cbrain/issues/1425

2025-03-03 22:00 UTC, prioux requested changes
This PR needs to be rebased, it contains tons of changes that are from other commits. Are you sure you started with the latest HEADs, originally?

2025-03-03 22:00 UTC, prioux commented on BrainPortal/app/assets/stylesheets/cbrain.css.erb
> +  height: 1.3em;
I'm ok with adding comments to the stylesheets, but why are you changing the styles themselves? That's not part of the PR's purpose. Was there something wrong with them? I created them to work with Safari, Chrome and Firefox, did you try all three?

2025-03-04 16:09 UTC, MontrealSergiy commented
> This PR needs to be rebased, it contains tons of changes that are from other commits. Are you sure you started with the latest HEADs, originally?

I guess I got confused should PR go to dev or master. I switched it to master, which seems to be the current policy, so irrelevant staff does not show now. Should I still do something else?

2025-03-04 16:09 UTC, MontrealSergiy commented on BrainPortal/app/assets/stylesheets/cbrain.css.erb
> +  height: 1.3em;
That's from somebody else commit.

2025-03-04 16:32 UTC, prioux commented on BrainPortal/app/views/layouts/_neurohub_secondary_navbar.html.erb
> +        <% if page_is_not?("#index", "#show") %>
Wrong logical operator. This is a bug.

2025-03-04 16:32 UTC, prioux commented on BrainPortal/app/views/data_providers/new.html.erb
> +      <%= f.select :type, grouped_options_for_select(@typelist), { :prompt => "Select Provider Type" } %><br/>
Why that change?

2025-03-04 16:38 UTC, prioux commented on BrainPortal/app/views/layouts/_neurohub_secondary_navbar.html.erb
> +        <% if page_is_not?("#index", "#show") %>
Wait let me think about this.

2025-03-05 15:57 UTC, prioux commented on BrainPortal/app/views/data_providers/new.html.erb
> +      <%= f.select :type, grouped_options_for_select(@typelist), { :prompt => "Select Provider Type" } %><br/>
OK I think you're right. This must have been old code because that form cannot be used for editing anymore. Thanks.

2025-03-05 16:28 UTC, prioux requested changes
Check my comments, I think there is only one bug.

2025-03-07 17:41 UTC, prioux commented
There is now a conflict because this PR changes one line in data_providers/new.html.erb that was also modified by a PR merged yesterday! Just fix manually please so we can merge.

2025-03-07 20:30 UTC, prioux commented
I think it worked. I'll merge the PR once the tests have finished.

2025-03-07 20:35 UTC, merged