File name verifier
aces/cbrain pull request #1451
Opened 2024-11-27 22:18 UTC by MontrealSergiy

2024-11-27 22:21 UTC, MontrealSergiy commented
Test boutiques [file_name_check.json](https://github.com/user-attachments/files/17940487/file_name_check.json)

2024-11-29 19:35 UTC, MontrealSergiy commented
Correcting

2025-01-16 19:56 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# For exmaple, in the "inputs" section:
Typo in `example`

2025-01-16 19:57 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# and in the "output-files" section:
Remove lines 38-47 in the comment block. We do not need to talk about the output-files section within the module's documentation, we are only validating String inputs to be properly formatted like CBRAIN file names.

2025-01-16 19:58 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# Please do not include output ids in the list. This modules does fully address more complex analyses, when output file name template includes several input string, or  prefixes or multiple path-temp
Remove comment at line 55-59, I think it's not necessary.

2025-01-16 20:26 UTC, MontrealSergiy commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +    verifs     = descriptor.custom_module_info('BoutiquesFileNameVerifier')
strange, I thought 
`self.custom            = self.custom || {}`
line in the BoutiquesSupport initializer takes care of empty custom block.

2025-01-16 20:29 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +    verifs     = descriptor.custom_module_info('BoutiquesFileNameVerifier')
For the `custom` level, not for the module's level

2025-01-16 20:32 UTC, MontrealSergiy commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +    verifs     = descriptor.custom_module_info('BoutiquesFileNameVerifier')
ok

2025-01-16 20:33 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +    verifs     = descriptor.custom_module_info('BoutiquesFileNameVerifier')
Descriptor 1:

```json
    "custom": {
        "cbrain:integrator_modules": {
            "BoutiquesFileNameVerifier" : [ "id1" ]
        }
    }
```

Descriptor 2:

```json
    "custom": {
        "cbrain:integrator_modules": {
        }
    }
```

In descriptor 1, `descriptor.custom_module_info('BoutiquesFileNameVerifier')` will return `[ "id1" ]`

In descriptor 2, it will return nil

2025-01-16 20:55 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# "cbrain:integrator_modules": {
Indent the JSON a bit further, int he comment block it now starts at the same level as the text, so it would not be rendered as a code block in the auto doc.

2025-01-16 21:05 UTC, MontrealSergiy commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# "cbrain:integrator_modules": {
line 38 was deleted as per a previous comment

2025-01-16 21:07 UTC, prioux requested changes

2025-01-16 21:07 UTC, prioux commented on BrainPortal/lib/boutiques_file_name_verifier.rb
> +# "cbrain:integrator_modules": {
I know. I mean the JSON is not indented properly anymore.

2025-01-16 21:40 UTC, merged